# SVM
https://stackabuse.com/implementing-svm-and-kernel-svm-with-pythons-scikit-learn/

In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline


In [2]:
bankdata = pd.read_csv("./data/data_banknote_authentication.txt")  
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [3]:
X = bankdata.drop('Class', axis=1)  
y = bankdata['Class'] 

In [4]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [5]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
y_pred = svclassifier.predict(X_test) 

In [7]:
ct = pd.crosstab(y_test, y_pred)
ct

col_0    0    1
Class          
0      152    4
1        0  119

# Kernel SVM

In [10]:
irisdata = pd.read_csv(
    filepath_or_buffer='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
    header=None, 
    sep=',')
irisdata.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']

In [12]:
X = irisdata.drop('class', axis=1)  
y = irisdata['class']  

In [13]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

### Polynomial Kernel

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix  

In [17]:
svclassifier = SVC(kernel='poly', degree=8)  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test) 

print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[12  0  0]
 [ 0  9  0]
 [ 0  1  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.89      0.94         9

    avg / total       0.97      0.97      0.97        30



### Gaussian Kernel

In [20]:
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test) 

print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[12  0  0]
 [ 0  9  0]
 [ 0  1  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.89      0.94         9

    avg / total       0.97      0.97      0.97        30



### Sigmoid

In [21]:
svclassifier = SVC(kernel='sigmoid')  
svclassifier.fit(X_train, y_train)  
y_pred = svclassifier.predict(X_test) 

print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[ 0  0 12]
 [ 0  0  9]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        12
Iris-versicolor       0.00      0.00      0.00         9
 Iris-virginica       0.30      1.00      0.46         9

    avg / total       0.09      0.30      0.14        30



/Users/tdeshpande/anaconda/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
